Name: server-api
Host: 0.0.0.0
Port: 5566


Postgres:
  DataSource: host=127.0.0.1 user=root password=public dbname=zecrey_treasureHunt port=5434 sslmode=disable

AccountName: "amber1"

Seed: ""

NftPrefix: "treasureHunt"

CollectionId: 6
