// Code generated by goctl. DO NOT EDIT.
package types

type ReqMintNft struct {
	RawMessage    string `form:"raw_message"`
	SignedMessage string `form:"signed_message"`
	AccountName   string `form:"account_name"`
	MediaId       string `form:"media_id"`
}

type RespMintNft struct {
	Id int64 `json:"id"`
}
